Repository ppy/osu-server-beatmap-submission, pull requests merged in 2025-01, with the labels that each got.

#16 Add rate limiting
  osu.Server.BeatmapSubmission/BeatmapSubmissionController.cs
  osu.Server.BeatmapSubmission/Program.cs
Labels: size/S

#18 Add checks for beatmap uploads being too large in size
  osu.Server.BeatmapSubmission.Tests/BeatmapSubmissionControllerTest.cs
  osu.Server.BeatmapSubmission/BeatmapSubmissionController.cs
Labels: size/L

#17 Adjust staging environment configuration
  README.md
  osu.Server.BeatmapSubmission.Tests/IntegrationTestWebApplicationFactory.cs
  osu.Server.BeatmapSubmission/Configuration/AppSettings.cs
  osu.Server.BeatmapSubmission/Program.cs
Labels: size/L

#19 👷 Add automated Docker builds and staging deployments
  .github/workflows/pack.yml
Labels: size/M

#20 💚 Fix Docker build context path
  .github/workflows/pack.yml
Labels: size/XS
