Repository ppy/osu-server-beatmap-submission, pull requests merged in 2025-02, with the labels that each got.

#21 Enable HTTP logging
  osu.Server.BeatmapSubmission/Program.cs
Labels: size/XS

#22 Fail & log requests where ASP.NET model binding failed
  osu.Server.BeatmapSubmission/ModelStateValidationFilter.cs
  osu.Server.BeatmapSubmission/Program.cs
Labels: size/M

#23 Do not purge beatmap if about to update it
  osu.Server.BeatmapSubmission.Tests/BeatmapSubmissionControllerTest.cs
  osu.Server.BeatmapSubmission/BeatmapSubmissionController.cs
  osu.Server.BeatmapSubmission/DatabaseOperationExtensions.cs
Labels: size/M

#24 Disallow non-ASCII characters in metadata which expects ASCII-only
  osu.Server.BeatmapSubmission.Tests/BeatmapSubmissionControllerTest.cs
  osu.Server.BeatmapSubmission.Tests/Resources/non-ascii-chars-in-ascii-metadata.osz
  osu.Server.BeatmapSubmission/Services/BeatmapPackageParser.cs
  osu.Server.BeatmapSubmission/osu.Server.BeatmapSubmission.csproj
Labels: size/M

#26 Add capability to allow access to service only for selected users
  README.md
  osu.Server.BeatmapSubmission/Configuration/AppSettings.cs
  osu.Server.BeatmapSubmission/Program.cs
  osu.Server.BeatmapSubmission/UserAllowListFilter.cs
Labels: size/L

#27 Rename "legacy IO" to "shared interop"
  README.md
  osu.Server.BeatmapSubmission.Tests/BeatmapSubmissionControllerTest.cs
  osu.Server.BeatmapSubmission/BeatmapSubmissionController.cs
  osu.Server.BeatmapSubmission/Configuration/AppSettings.cs
  osu.Server.BeatmapSubmission/Program.cs
  osu.Server.BeatmapSubmission/Services/ISharedInterop.cs
  osu.Server.BeatmapSubmission/Services/SharedInterop.cs
Labels: size/M

#28 👷 Add GHA production deployments
  .github/workflows/pack.yml
Labels: size/M

#29 Add envvars for configuring S3 bucket regions
  README.md
  osu.Server.BeatmapSubmission/Configuration/AppSettings.cs
  osu.Server.BeatmapSubmission/Program.cs
  osu.Server.BeatmapSubmission/Services/S3BeatmapStorage.cs
Labels: size/M

#31 Set 'notify on discussion replies' state according to user request
  osu.Server.BeatmapSubmission/BeatmapSubmissionController.cs
  osu.Server.BeatmapSubmission/DatabaseOperationExtensions.cs
  osu.Server.BeatmapSubmission/Models/API/Requests/PutBeatmapSetRequest.cs
Labels: size/M

#33 Bump incoming file size limit to 200MB
  osu.Server.BeatmapSubmission/BeatmapSubmissionController.cs
  osu.Server.BeatmapSubmission/Program.cs
Labels: size/S

#36 Fix hard crash when BeatmapSetID is completely missing from an `.osu` file
  osu.Server.BeatmapSubmission.Tests/BeatmapSubmissionControllerTest.cs
  osu.Server.BeatmapSubmission.Tests/Resources/no-beatmap-set-id.osz
  osu.Server.BeatmapSubmission/Services/BeatmapPackageParser.cs
Labels: size/M
